[2023-11-24T20:36:55.872+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_extract_despesas.task_extract_despesas scheduled__2023-11-24T20:26:32.148764+00:00 [queued]>
[2023-11-24T20:36:55.882+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_extract_despesas.task_extract_despesas scheduled__2023-11-24T20:26:32.148764+00:00 [queued]>
[2023-11-24T20:36:55.883+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2023-11-24T20:36:55.897+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_extract_despesas> on 2023-11-24 20:26:32.148764+00:00
[2023-11-24T20:36:55.904+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2023-11-24T20:36:55.907+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_extract_despesas', 'task_extract_despesas', 'scheduled__2023-11-24T20:26:32.148764+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/dag_extract_despesas.py', '--cfg-path', '/tmp/tmpb31mieh9']
[2023-11-24T20:36:55.908+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask task_extract_despesas
[2023-11-24T20:36:55.959+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_extract_despesas.task_extract_despesas scheduled__2023-11-24T20:26:32.148764+00:00 [running]> on host eea2b93d502c
[2023-11-24T20:36:56.070+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_extract_despesas' AIRFLOW_CTX_TASK_ID='task_extract_despesas' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T20:26:32.148764+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-24T20:26:32.148764+00:00'
[2023-11-24T20:36:58.347+0000] {logging_mixin.py:154} INFO - Despesas do deputado 215043 do mês 11 extraída!
[2023-11-24T20:36:58.350+0000] {logging_mixin.py:154} INFO - Lote de despesas de 215043 do mês 11 adicionado!
[2023-11-24T20:37:00.451+0000] {logging_mixin.py:154} INFO - Despesas do deputado 139285 do mês 11 extraída!
[2023-11-24T20:37:00.454+0000] {logging_mixin.py:154} INFO - Lote de despesas de 139285 do mês 11 adicionado!
[2023-11-24T20:37:02.591+0000] {logging_mixin.py:154} INFO - Despesas do deputado 157130 do mês 11 extraída!
[2023-11-24T20:37:02.595+0000] {logging_mixin.py:154} INFO - Lote de despesas de 157130 do mês 11 adicionado!
[2023-11-24T20:37:04.677+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73768 do mês 11 extraída!
[2023-11-24T20:37:04.681+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73768 do mês 11 adicionado!
[2023-11-24T20:37:06.744+0000] {logging_mixin.py:154} INFO - Despesas do deputado 210989 do mês 11 extraída!
[2023-11-24T20:37:06.747+0000] {logging_mixin.py:154} INFO - Lote de despesas de 210989 do mês 11 adicionado!
[2023-11-24T20:37:08.810+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73778 do mês 11 extraída!
[2023-11-24T20:37:08.815+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73778 do mês 11 adicionado!
[2023-11-24T20:37:10.897+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73788 do mês 11 extraída!
[2023-11-24T20:37:10.907+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73788 do mês 11 adicionado!
[2023-11-24T20:37:12.962+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73801 do mês 11 extraída!
[2023-11-24T20:37:12.965+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73801 do mês 11 adicionado!
[2023-11-24T20:37:15.036+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73806 do mês 11 extraída!
[2023-11-24T20:37:15.039+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73806 do mês 11 adicionado!
[2023-11-24T20:37:17.108+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141391 do mês 11 extraída!
[2023-11-24T20:37:17.114+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141391 do mês 11 adicionado!
[2023-11-24T20:37:19.188+0000] {logging_mixin.py:154} INFO - Despesas do deputado 73808 do mês 11 extraída!
[2023-11-24T20:37:19.204+0000] {logging_mixin.py:154} INFO - Lote de despesas de 73808 do mês 11 adicionado!
[2023-11-24T20:37:21.264+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141398 do mês 11 extraída!
[2023-11-24T20:37:21.268+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141398 do mês 11 adicionado!
[2023-11-24T20:37:23.318+0000] {logging_mixin.py:154} INFO - Despesas do deputado 122974 do mês 11 extraída!
[2023-11-24T20:37:23.324+0000] {logging_mixin.py:154} INFO - Lote de despesas de 122974 do mês 11 adicionado!
[2023-11-24T20:37:25.493+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141408 do mês 11 extraída!
[2023-11-24T20:37:25.501+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141408 do mês 11 adicionado!
[2023-11-24T20:37:27.614+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141411 do mês 11 extraída!
[2023-11-24T20:37:27.622+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141411 do mês 11 adicionado!
[2023-11-24T20:37:29.682+0000] {logging_mixin.py:154} INFO - Despesas do deputado 104552 do mês 11 extraída!
[2023-11-24T20:37:29.691+0000] {logging_mixin.py:154} INFO - Lote de despesas de 104552 do mês 11 adicionado!
[2023-11-24T20:37:31.753+0000] {logging_mixin.py:154} INFO - Despesas do deputado 225386 do mês 11 extraída!
[2023-11-24T20:37:31.769+0000] {logging_mixin.py:154} INFO - Lote de despesas de 225386 do mês 11 adicionado!
[2023-11-24T20:37:33.816+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141421 do mês 11 extraída!
[2023-11-24T20:37:33.820+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141421 do mês 11 adicionado!
[2023-11-24T20:37:35.837+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141431 do mês 11 extraída!
[2023-11-24T20:37:35.841+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141431 do mês 11 adicionado!
[2023-11-24T20:37:37.890+0000] {logging_mixin.py:154} INFO - Despesas do deputado 198783 do mês 11 extraída!
[2023-11-24T20:37:37.894+0000] {logging_mixin.py:154} INFO - Lote de despesas de 198783 do mês 11 adicionado!
[2023-11-24T20:37:39.963+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141450 do mês 11 extraída!
[2023-11-24T20:37:39.977+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141450 do mês 11 adicionado!
[2023-11-24T20:37:42.033+0000] {logging_mixin.py:154} INFO - Despesas do deputado 221328 do mês 11 extraída!
[2023-11-24T20:37:42.038+0000] {logging_mixin.py:154} INFO - Lote de despesas de 221328 do mês 11 adicionado!
[2023-11-24T20:37:44.118+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141456 do mês 11 extraída!
[2023-11-24T20:37:44.132+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141456 do mês 11 adicionado!
[2023-11-24T20:37:46.205+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141458 do mês 11 extraída!
[2023-11-24T20:37:46.213+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141458 do mês 11 adicionado!
[2023-11-24T20:37:48.289+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141459 do mês 11 extraída!
[2023-11-24T20:37:48.292+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141459 do mês 11 adicionado!
[2023-11-24T20:37:50.363+0000] {logging_mixin.py:154} INFO - Despesas do deputado 221329 do mês 11 extraída!
[2023-11-24T20:37:50.369+0000] {logging_mixin.py:154} INFO - Lote de despesas de 221329 do mês 11 adicionado!
[2023-11-24T20:37:52.427+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141464 do mês 11 extraída!
[2023-11-24T20:37:52.438+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141464 do mês 11 adicionado!
[2023-11-24T20:37:54.616+0000] {logging_mixin.py:154} INFO - Despesas do deputado 221338 do mês 11 extraída!
[2023-11-24T20:37:54.620+0000] {logging_mixin.py:154} INFO - Lote de despesas de 221338 do mês 11 adicionado!
[2023-11-24T20:37:56.686+0000] {logging_mixin.py:154} INFO - Despesas do deputado 221339 do mês 11 extraída!
[2023-11-24T20:37:56.696+0000] {logging_mixin.py:154} INFO - Lote de despesas de 221339 do mês 11 adicionado!
[2023-11-24T20:37:58.768+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141470 do mês 11 extraída!
[2023-11-24T20:37:58.772+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141470 do mês 11 adicionado!
[2023-11-24T20:38:00.783+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141480 do mês 11 extraída!
[2023-11-24T20:38:00.786+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141480 do mês 11 adicionado!
[2023-11-24T20:38:02.829+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141485 do mês 11 extraída!
[2023-11-24T20:38:02.833+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141485 do mês 11 adicionado!
[2023-11-24T20:38:04.887+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141487 do mês 11 extraída!
[2023-11-24T20:38:04.890+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141487 do mês 11 adicionado!
[2023-11-24T20:38:06.935+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141488 do mês 11 extraída!
[2023-11-24T20:38:06.939+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141488 do mês 11 adicionado!
[2023-11-24T20:38:09.061+0000] {logging_mixin.py:154} INFO - Despesas do deputado 92346 do mês 11 extraída!
[2023-11-24T20:38:09.067+0000] {logging_mixin.py:154} INFO - Lote de despesas de 92346 do mês 11 adicionado!
[2023-11-24T20:38:11.134+0000] {logging_mixin.py:154} INFO - Despesas do deputado 88256 do mês 11 extraída!
[2023-11-24T20:38:11.137+0000] {logging_mixin.py:154} INFO - Lote de despesas de 88256 do mês 11 adicionado!
[2023-11-24T20:38:13.276+0000] {logging_mixin.py:154} INFO - Despesas do deputado 221378 do mês 11 extraída!
[2023-11-24T20:38:13.282+0000] {logging_mixin.py:154} INFO - Lote de despesas de 221378 do mês 11 adicionado!
[2023-11-24T20:38:15.483+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141516 do mês 11 extraída!
[2023-11-24T20:38:15.493+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141516 do mês 11 adicionado!
[2023-11-24T20:38:17.566+0000] {logging_mixin.py:154} INFO - Despesas do deputado 123086 do mês 11 extraída!
[2023-11-24T20:38:17.570+0000] {logging_mixin.py:154} INFO - Lote de despesas de 123086 do mês 11 adicionado!
[2023-11-24T20:38:19.670+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141531 do mês 11 extraída!
[2023-11-24T20:38:19.681+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141531 do mês 11 adicionado!
[2023-11-24T20:38:21.767+0000] {logging_mixin.py:154} INFO - Despesas do deputado 69871 do mês 11 extraída!
[2023-11-24T20:38:21.770+0000] {logging_mixin.py:154} INFO - Lote de despesas de 69871 do mês 11 adicionado!
[2023-11-24T20:38:23.861+0000] {logging_mixin.py:154} INFO - Despesas do deputado 141555 do mês 11 extraída!
[2023-11-24T20:38:23.872+0000] {logging_mixin.py:154} INFO - Lote de despesas de 141555 do mês 11 adicionado!
[2023-11-24T20:38:25.894+0000] {logging_mixin.py:154} INFO - Despesas do deputado 143632 do mês 11 extraída!
[2023-11-24T20:38:25.896+0000] {logging_mixin.py:154} INFO - Lote de despesas de 143632 do mês 11 adicionado!
[2023-11-24T20:38:27.939+0000] {logging_mixin.py:154} INFO - Despesas do deputado 162067 do mês 11 extraída!
[2023-11-24T20:38:27.943+0000] {logging_mixin.py:154} INFO - Lote de despesas de 162067 do mês 11 adicionado!
[2023-11-24T20:38:30.040+0000] {logging_mixin.py:154} INFO - Despesas do deputado 213274 do mês 11 extraída!
[2023-11-24T20:38:30.050+0000] {logging_mixin.py:154} INFO - Lote de despesas de 213274 do mês 11 adicionado!
[2023-11-24T20:38:32.099+0000] {logging_mixin.py:154} INFO - Despesas do deputado 209189 do mês 11 extraída!
[2023-11-24T20:38:32.105+0000] {logging_mixin.py:154} INFO - Lote de despesas de 209189 do mês 11 adicionado!
[2023-11-24T20:38:34.182+0000] {logging_mixin.py:154} INFO - Despesas do deputado 98615 do mês 11 extraída!
[2023-11-24T20:38:34.190+0000] {logging_mixin.py:154} INFO - Lote de despesas de 98615 do mês 11 adicionado!
[2023-11-24T20:38:36.253+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74041 do mês 11 extraída!
[2023-11-24T20:38:36.256+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74041 do mês 11 adicionado!
[2023-11-24T20:38:38.318+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74043 do mês 11 extraída!
[2023-11-24T20:38:38.323+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74043 do mês 11 adicionado!
[2023-11-24T20:38:40.380+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74044 do mês 11 extraída!
[2023-11-24T20:38:40.383+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74044 do mês 11 adicionado!
[2023-11-24T20:38:42.444+0000] {logging_mixin.py:154} INFO - Despesas do deputado 133439 do mês 11 extraída!
[2023-11-24T20:38:42.454+0000] {logging_mixin.py:154} INFO - Lote de despesas de 133439 do mês 11 adicionado!
[2023-11-24T20:38:44.580+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74057 do mês 11 extraída!
[2023-11-24T20:38:44.586+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74057 do mês 11 adicionado!
[2023-11-24T20:38:46.646+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74060 do mês 11 extraída!
[2023-11-24T20:38:46.659+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74060 do mês 11 adicionado!
[2023-11-24T20:38:48.800+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74075 do mês 11 extraída!
[2023-11-24T20:38:48.803+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74075 do mês 11 adicionado!
[2023-11-24T20:38:50.833+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74079 do mês 11 extraída!
[2023-11-24T20:38:50.837+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74079 do mês 11 adicionado!
[2023-11-24T20:38:52.922+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74084 do mês 11 extraída!
[2023-11-24T20:38:52.927+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74084 do mês 11 adicionado!
[2023-11-24T20:38:55.018+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74090 do mês 11 extraída!
[2023-11-24T20:38:55.024+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74090 do mês 11 adicionado!
[2023-11-24T20:38:57.134+0000] {logging_mixin.py:154} INFO - Despesas do deputado 217480 do mês 11 extraída!
[2023-11-24T20:38:57.137+0000] {logging_mixin.py:154} INFO - Lote de despesas de 217480 do mês 11 adicionado!
[2023-11-24T20:38:59.176+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74141 do mês 11 extraída!
[2023-11-24T20:38:59.180+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74141 do mês 11 adicionado!
[2023-11-24T20:39:01.228+0000] {logging_mixin.py:154} INFO - Despesas do deputado 160161 do mês 11 extraída!
[2023-11-24T20:39:01.232+0000] {logging_mixin.py:154} INFO - Lote de despesas de 160161 do mês 11 adicionado!
[2023-11-24T20:39:03.529+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74156 do mês 11 extraída!
[2023-11-24T20:39:03.540+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74156 do mês 11 adicionado!
[2023-11-24T20:39:05.629+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74158 do mês 11 extraída!
[2023-11-24T20:39:05.636+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74158 do mês 11 adicionado!
[2023-11-24T20:39:07.681+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74159 do mês 11 extraída!
[2023-11-24T20:39:07.684+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74159 do mês 11 adicionado!
[2023-11-24T20:39:09.773+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74160 do mês 11 extraída!
[2023-11-24T20:39:09.776+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74160 do mês 11 adicionado!
[2023-11-24T20:39:11.811+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74161 do mês 11 extraída!
[2023-11-24T20:39:11.815+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74161 do mês 11 adicionado!
[2023-11-24T20:39:13.917+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74171 do mês 11 extraída!
[2023-11-24T20:39:13.922+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74171 do mês 11 adicionado!
[2023-11-24T20:39:15.973+0000] {logging_mixin.py:154} INFO - Despesas do deputado 225727 do mês 11 extraída!
[2023-11-24T20:39:15.984+0000] {logging_mixin.py:154} INFO - Lote de despesas de 225727 do mês 11 adicionado!
[2023-11-24T20:39:18.051+0000] {logging_mixin.py:154} INFO - Despesas do deputado 219585 do mês 11 extraída!
[2023-11-24T20:39:18.058+0000] {logging_mixin.py:154} INFO - Lote de despesas de 219585 do mês 11 adicionado!
[2023-11-24T20:39:20.109+0000] {logging_mixin.py:154} INFO - Despesas do deputado 225730 do mês 11 extraída!
[2023-11-24T20:39:20.116+0000] {logging_mixin.py:154} INFO - Lote de despesas de 225730 do mês 11 adicionado!
[2023-11-24T20:39:22.155+0000] {logging_mixin.py:154} INFO - Despesas do deputado 163321 do mês 11 extraída!
[2023-11-24T20:39:22.158+0000] {logging_mixin.py:154} INFO - Lote de despesas de 163321 do mês 11 adicionado!
[2023-11-24T20:39:24.222+0000] {logging_mixin.py:154} INFO - Despesas do deputado 166402 do mês 11 extraída!
[2023-11-24T20:39:24.237+0000] {logging_mixin.py:154} INFO - Lote de despesas de 166402 do mês 11 adicionado!
[2023-11-24T20:39:26.279+0000] {logging_mixin.py:154} INFO - Despesas do deputado 164360 do mês 11 extraída!
[2023-11-24T20:39:26.283+0000] {logging_mixin.py:154} INFO - Lote de despesas de 164360 do mês 11 adicionado!
[2023-11-24T20:39:28.324+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74253 do mês 11 extraída!
[2023-11-24T20:39:28.327+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74253 do mês 11 adicionado!
[2023-11-24T20:39:30.360+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74262 do mês 11 extraída!
[2023-11-24T20:39:30.363+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74262 do mês 11 adicionado!
[2023-11-24T20:39:32.391+0000] {logging_mixin.py:154} INFO - Despesas do deputado 226837 do mês 11 extraída!
[2023-11-24T20:39:32.399+0000] {logging_mixin.py:154} INFO - Lote de despesas de 226837 do mês 11 adicionado!
[2023-11-24T20:39:34.456+0000] {logging_mixin.py:154} INFO - Despesas do deputado 92699 do mês 11 extraída!
[2023-11-24T20:39:34.465+0000] {logging_mixin.py:154} INFO - Lote de despesas de 92699 do mês 11 adicionado!
[2023-11-24T20:39:36.547+0000] {logging_mixin.py:154} INFO - Despesas do deputado 162332 do mês 11 extraída!
[2023-11-24T20:39:36.550+0000] {logging_mixin.py:154} INFO - Lote de despesas de 162332 do mês 11 adicionado!
[2023-11-24T20:39:38.579+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74270 do mês 11 extraída!
[2023-11-24T20:39:38.582+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74270 do mês 11 adicionado!
[2023-11-24T20:39:40.650+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74356 do mês 11 extraída!
[2023-11-24T20:39:40.653+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74356 do mês 11 adicionado!
[2023-11-24T20:39:42.681+0000] {logging_mixin.py:154} INFO - Despesas do deputado 156190 do mês 11 extraída!
[2023-11-24T20:39:42.685+0000] {logging_mixin.py:154} INFO - Lote de despesas de 156190 do mês 11 adicionado!
[2023-11-24T20:39:44.774+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74273 do mês 11 extraída!
[2023-11-24T20:39:44.782+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74273 do mês 11 adicionado!
[2023-11-24T20:39:46.836+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74283 do mês 11 extraída!
[2023-11-24T20:39:46.845+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74283 do mês 11 adicionado!
[2023-11-24T20:39:48.915+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74299 do mês 11 extraída!
[2023-11-24T20:39:48.918+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74299 do mês 11 adicionado!
[2023-11-24T20:39:50.952+0000] {logging_mixin.py:154} INFO - Despesas do deputado 154178 do mês 11 extraída!
[2023-11-24T20:39:50.956+0000] {logging_mixin.py:154} INFO - Lote de despesas de 154178 do mês 11 adicionado!
[2023-11-24T20:39:53.013+0000] {logging_mixin.py:154} INFO - Despesas do deputado 143942 do mês 11 extraída!
[2023-11-24T20:39:53.016+0000] {logging_mixin.py:154} INFO - Lote de despesas de 143942 do mês 11 adicionado!
[2023-11-24T20:39:55.132+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74317 do mês 11 extraída!
[2023-11-24T20:39:55.137+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74317 do mês 11 adicionado!
[2023-11-24T20:39:57.207+0000] {logging_mixin.py:154} INFO - Despesas do deputado 92776 do mês 11 extraída!
[2023-11-24T20:39:57.211+0000] {logging_mixin.py:154} INFO - Lote de despesas de 92776 do mês 11 adicionado!
[2023-11-24T20:39:59.316+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74371 do mês 11 extraída!
[2023-11-24T20:39:59.321+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74371 do mês 11 adicionado!
[2023-11-24T20:40:01.340+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74374 do mês 11 extraída!
[2023-11-24T20:40:01.345+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74374 do mês 11 adicionado!
[2023-11-24T20:40:03.375+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74376 do mês 11 extraída!
[2023-11-24T20:40:03.378+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74376 do mês 11 adicionado!
[2023-11-24T20:40:05.453+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178829 do mês 11 extraída!
[2023-11-24T20:40:05.463+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178829 do mês 11 adicionado!
[2023-11-24T20:40:07.524+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74383 do mês 11 extraída!
[2023-11-24T20:40:07.533+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74383 do mês 11 adicionado!
[2023-11-24T20:40:09.553+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178832 do mês 11 extraída!
[2023-11-24T20:40:09.556+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178832 do mês 11 adicionado!
[2023-11-24T20:40:11.635+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178835 do mês 11 extraída!
[2023-11-24T20:40:11.643+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178835 do mês 11 adicionado!
[2023-11-24T20:40:13.720+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178843 do mês 11 extraída!
[2023-11-24T20:40:13.723+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178843 do mês 11 adicionado!
[2023-11-24T20:40:15.808+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74398 do mês 11 extraída!
[2023-11-24T20:40:15.819+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74398 do mês 11 adicionado!
[2023-11-24T20:40:17.851+0000] {logging_mixin.py:154} INFO - Despesas do deputado 74400 do mês 11 extraída!
[2023-11-24T20:40:17.861+0000] {logging_mixin.py:154} INFO - Lote de despesas de 74400 do mês 11 adicionado!
[2023-11-24T20:40:19.903+0000] {logging_mixin.py:154} INFO - Despesas do deputado 205476 do mês 11 extraída!
[2023-11-24T20:40:19.906+0000] {logging_mixin.py:154} INFO - Lote de despesas de 205476 do mês 11 adicionado!
[2023-11-24T20:40:21.972+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178854 do mês 11 extraída!
[2023-11-24T20:40:21.976+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178854 do mês 11 adicionado!
[2023-11-24T20:40:24.073+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178857 do mês 11 extraída!
[2023-11-24T20:40:24.077+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178857 do mês 11 adicionado!
[2023-11-24T20:40:26.116+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178858 do mês 11 extraída!
[2023-11-24T20:40:26.118+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178858 do mês 11 adicionado!
[2023-11-24T20:40:28.157+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178860 do mês 11 extraída!
[2023-11-24T20:40:28.161+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178860 do mês 11 adicionado!
[2023-11-24T20:40:30.212+0000] {logging_mixin.py:154} INFO - Despesas do deputado 178866 do mês 11 extraída!
[2023-11-24T20:40:30.215+0000] {logging_mixin.py:154} INFO - Lote de despesas de 178866 do mês 11 adicionado!
[2023-11-24T20:40:48.990+0000] {logging_mixin.py:154} INFO - Erro ao requisitar as despesas do deputado 133810 para 2023/11: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf5dfe760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-24T20:40:48.964+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-24T20:42:53.802+0000] {logging_mixin.py:154} INFO - Erro ao requisitar as despesas do deputado 133810 para 2023/11: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf06635e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-24T20:43:29.880+0000] {logging_mixin.py:154} INFO - Erro ao requisitar as despesas do deputado 133810 para 2023/11: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf5d93880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-24T20:43:29.813+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-24T20:47:34.005+0000] {logging_mixin.py:154} INFO - Erro ao requisitar as despesas do deputado 133810 para 2023/11: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf0663b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-24T20:47:39.862+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-24T20:48:14.692+0000] {logging_mixin.py:154} INFO - Erro ao requisitar as despesas do deputado 133810 para 2023/11: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf5d93d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-11-24T20:48:21.819+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-24T20:48:21.985+0000] {local_task_job_runner.py:205} ERROR - Heartbeat time limit exceeded!
[2023-11-24T20:48:47.240+0000] {process_utils.py:131} INFO - Sending 15 to group 79. PIDs of all processes in the group: [79]
[2023-11-24T20:49:01.267+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 79
[2023-11-24T20:49:08.838+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-11-24T20:49:12.809+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7bf0663430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf0663430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/get_despesas_stg.py", line 29, in getDespesasDeputado
    response = session.get(url, timeout=120)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dadosabertos.camara.leg.br', port=443): Max retries exceeded with url: /api/v2/deputados/133810/despesas?ano=2023&mes=11&itens=80&ordem=ASC&ordenarPor=ano (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7bf0663430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/get_despesas_stg.py", line 99, in extractDespesas
    df_despesas = getAllDespesas(ids, data.month, data.year)
  File "/opt/airflow/dags/scripts/get_despesas_stg.py", line 82, in getAllDespesas
    df_despesas = getDespesasDeputado(id_deputado, mes, ano)
  File "/opt/airflow/dags/scripts/get_despesas_stg.py", line 58, in getDespesasDeputado
    print(f"Erro ao requisitar as despesas do deputado {id_deputado} para {ano}/{mes}: {e}")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 166, in write
    self.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 173, in flush
    self._propagate_log(buf)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 154, in _propagate_log
    self.logger.log(self.level, remove_escape_codes(message))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 61, in remove_escape_codes
    return ANSI_ESCAPE.sub("", text)
  File "/home/airflow/.local/lib/python3.8/site-packages/re2.py", line 291, in sub
    joined_pieces, _ = self.subn(repl, text, count)
  File "/home/airflow/.local/lib/python3.8/site-packages/re2.py", line 286, in subn
    pieces, numsplit = self._split(cb, text, count)
  File "/home/airflow/.local/lib/python3.8/site-packages/re2.py", line 270, in _split
    for match in matchiter:
  File "/home/airflow/.local/lib/python3.8/site-packages/re2.py", line 184, in _match
    spans = self._regexp.Match(anchor, encoded_text, encoded_pos,
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-11-24T20:49:40.687+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=79, status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:36:55') (79) terminated with exit code -9
[2023-11-24T20:49:40.765+0000] {standard_task_runner.py:172} ERROR - Job 122 was killed before it finished (likely due to running out of memory)
